GET http://localhost:8000/categorias
###
POST http://localhost:8000/categorias
Content-Type: application/json

{
    "nombreCategoria": "Dairo",
    "valorLimite": "2000",
    "idUsuario": "1"
}
###
PUT http://localhost:8000/categorias/3
Content-Type: application/json

{
    "nombreCategoria": "Dairobbbb",
    "valorLimite": "5000",
    "idUsuario": "1"
}
###
DELETE http://localhost:8000/categorias/3


//Tabla Cuenta
###
GET http://localhost:8000/cuentas
###
POST http://localhost:8000/cuentas
Content-Type: application/json

{
    "idUsuario": "2",
    "idTipoCuenta": "2",
    "nombreCuenta": "bancolombia",
    "saldo":"200000"
}
###
PUT http://localhost:8000/cuentas/1
Content-Type: application/json

{
   "idUsuario": "2",
    "idTipoCuenta": "2",
    "nombreCuenta": "bancolombia",
    "saldo":"500000"

}
###
DELETE http://localhost:8000/cuentas/4


//tipoFinanaza
###
GET http://localhost:8000/TipoFinanza
###
POST http://localhost:8000/TipoFinanza
Content-Type: application/json

{
      "nombreTipoFinanza": "nnnnnasas"
}
###
PUT http://localhost:8000/TipoFinanza/3
Content-Type: application/json

{
    "nombreTipoFinanza": "gordoo"
}
###
DELETE http://localhost:8000/TipoFinanza/2
