GET http://localhost:8000/Transaccionget
### 

PUT http://localhost:8000/transacciones/2
Content-Type: application/json

{
  "idTransaccion": 1,
  "valorMonto": 1000.5,
  "fecha": "2025-06-12",
  "descripcion": "Pago actualizado",
  "idTipoFinanza": 2,
  "idCategoria": 3,
  "idCuenta": 1
}




###
PUT http://localhost:8000/Transaccionput/1
Content-Type: application/json

{
    "idTransaccion":  8,
     "valorMonto": 10000.80,
    "fecha": "2004-05-02",
    "descripcion": "gastos de encime",
    "idTipoFinanza": 1 ,
    "idCategoria": 1 ,
    "idCuenta": 1 ,
}
###

DELETE http://localhost:8000/Transacciondelete/9